AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for ZenHubToTeams

Globals:
  Function:
    Timeout: 10
    Runtime: dotnetcore3.1

Parameters:
  TeamsWebhook:
    Type: String

Resources:
  ProcessWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: WebhookProcessing::WebhookProcessing.Processor::Invoke
      Environment:
        Variables:
          TEAMS_WEBHOOK: !Ref TeamsWebhook
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /event
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Process function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/event/"